/*
 * Apigee Cache Microservice
 * Create a microservice that will perform CRUD operations on Apigee Edge cache.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dmandar@pkglobal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.prokarma.apigee.caches.domain;

import java.util.Objects;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * It represents the successful response of the Api
 */
@ApiModel(description = "It represents the successful response of the Api")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-12-03T08:03:39.782Z")
public class CacheResponse   {
  @JsonProperty("status")
  private String status = null;

  @JsonProperty("message")
  private Object message = null;

  public CacheResponse status(String status) {
    this.status = status;
    return this;
  }

  /**
   * The status will always be success.
   * @return status
   **/
  @JsonProperty("status")
  @ApiModelProperty(example = "success", required = true, value = "The status will always be success.")
  @NotNull
 @Pattern(regexp="^[success]$")  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public CacheResponse message(Object message) {
    this.message = message;
    return this;
  }

  /**
   * A human-readable message describing the success message.
   * @return message
   **/
  @JsonProperty("message")
  @ApiModelProperty(example = "\"Cache created successfully in Apigee Edge.\"", required = true, value = "A human-readable message describing the success message.")
  @NotNull
  public Object getMessage() {
    return message;
  }

  public void setMessage(Object message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CacheResponse cacheResponse = (CacheResponse) o;
    return Objects.equals(this.status, cacheResponse.status) &&
        Objects.equals(this.message, cacheResponse.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CacheResponse {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

