/*
 * Apigee Cache Microservice Create a microservice that will perform CRUD operations on Apigee Edge
 * cache.
 *
 * OpenAPI spec version: 1.0.0 Contact: dmandar@pkglobal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class manually.
 */


package com.prokarma.apigee.caches.domain;

import java.util.Objects;
import javax.validation.Valid;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Deprecated. Size threshold above which cache entries will be compressed. If not specified,
 * compression is disabled.
 **/
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(
    description = "Deprecated. Size threshold above which cache entries will be compressed. If not specified, compression is disabled.")

public class CacheRequestCompression {

  private @Valid Integer minimumSize = null;

  /**
   * Size threshold, in KBs, above which cache entries will be compressed.
   **/
  public CacheRequestCompression minimumSize(Integer minimumSize) {
    this.minimumSize = minimumSize;
    return this;
  }


  @ApiModelProperty(example = "0",
      value = "Size threshold, in KBs, above which cache entries will be compressed.")
  @JsonProperty("minimumSize")
  public Integer getMinimumSize() {
    return minimumSize;
  }

  public void setMinimumSize(Integer minimumSize) {
    this.minimumSize = minimumSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CacheRequestCompression cacheRequestCompression = (CacheRequestCompression) o;
    return Objects.equals(minimumSize, cacheRequestCompression.minimumSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minimumSize);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CacheRequestCompression {\n");

    sb.append("    minimumSize: ").append(toIndentedString(minimumSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
